# OpenCV

### OpenCV Installation
Anacona promt-pip install opencv-python

In [1]:
import cv2 
import numpy as np

#### Load/Read Images

In [3]:
img=cv2.imread("F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg",1)

#### Lets take a closer look at how images are stored

In [4]:
print(img)

[[[227 216 212]
  [225 214 210]
  [226 215 211]
  ...
  [ 60  58  58]
  [ 65  60  61]
  [ 35  30  31]]

 [[227 216 212]
  [225 214 210]
  [226 215 211]
  ...
  [ 65  63  63]
  [ 67  62  63]
  [ 33  28  29]]

 [[225 214 210]
  [224 213 209]
  [226 215 211]
  ...
  [ 66  63  65]
  [ 63  58  59]
  [ 30  25  26]]

 ...

 [[ 50  39  72]
  [ 57  45  81]
  [ 57  43  84]
  ...
  [229 220 217]
  [229 219 219]
  [227 217 217]]

 [[ 45  34  66]
  [ 52  41  74]
  [ 52  39  77]
  ...
  [228 219 216]
  [229 219 219]
  [228 218 218]]

 [[ 40  30  60]
  [ 38  27  59]
  [ 36  24  60]
  ...
  [227 218 215]
  [229 219 219]
  [229 219 219]]]


In [5]:
img.shape

(1455, 1134, 3)

In [6]:
img.shape[0] #height

1455

In [7]:
img.shape[1] #Width

1134

## display the Image

In [9]:
cv2.imshow('Shalem_Bheemadolu',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
img=cv2.imread("F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg",0)
cv2.imshow('shalem_B/W',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread("F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg",1)
cv2.imshow('shalem',img)
cv2.waitKey()
cv2.destroyAllWindows()

## Save Image

In [13]:
img=cv2.imread("F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg",0)
cv2.imshow('shalem',img)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.imwrite('shalem_b_w.jpg',img)

True

## Resize Image

In [14]:
img.shape[0]*0.5

727.5

In [15]:
img.shape[1]*0.5

567.0

In [16]:
img=cv2.imread("F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg")
resized_image=cv2.resize(img,(727,567))
cv2.imshow('shalem',resized_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Face detection using HAAR Cascade Classifiers

In [18]:
face_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_frontalface_default.xml')

# Load the image and convert it into grayscale

image=cv2.imread('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg')
image=cv2.resize(image,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.05,5)

In [19]:
print(faces)

[[143  70 212 212]]


In [26]:
face_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_frontalface_default.xml')

# Load the image and convert it into grayscale

image=cv2.imread('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg')
resize_image=cv2.resize(image,(500,500))
gray=cv2.cvtColor(resize_image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.05,5)

if faces is ():
    print('No faces found')
    
for (x,y,w,h) in faces:
    cv2.rectangle(resize_image,(x,y),(x+w,y+h),(100,255,100),1)  #(B,G,R)

    cv2.imshow('Face detection',resize_image)
    cv2.waitKey()
    cv2.destroyAllWindows()

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-26-4e335d02e003>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


### Face and eye detection using HAAR Cascade Classifiers in Image

In [30]:
face_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_eye.xml')

# Load the image and convert it into grayscale

image=cv2.imread('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/shalem.jpg')
resize_image=cv2.resize(image,(500,500))
gray=cv2.cvtColor(resize_image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.3,5)

if faces is ():
    print('No faces found')
    
for (x,y,w,h) in faces:
    cv2.rectangle(resize_image,(x,y),(x+w,y+h),(0,255,0),2)  #(B,G,R)
    roi_gray=gray[y:y+h,x:x+w]
    roi_color=resize_image[y:y+h,x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,0,255),2)
        
        

    cv2.imshow('Shalem_Bheemadolu',resize_image)
    cv2.waitKey()
    cv2.destroyAllWindows()

<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-30-16c59458b6bf>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


### Capture a Video

In [31]:
# doing some face recognition from webcam
import cv2
video=cv2.VideoCapture(0) # 0 is for webcam

while True:
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1)==ord('r'):
        break

video.release()
cv2.destroyAllWindows()

### Face and eye detection using HAAR Cascade Classifiers in Video

In [33]:
face_cascade=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_frontalface_default.xml')
eye_cascade=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_eye.xml')

# Load the image and convert it into grayscale

def detect(gray,frame):
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)  #(B,G,R)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=frame[y:y+h,x:x+w]
        eyes=eye_cascade.detectMultiScale(roi_gray,1.1,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,0,255),2)
    return frame

# doing some face recognition from webcam

video=cv2.VideoCapture(0) # 0 is for webcam

while True:
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas=detect(gray,frame)
    cv2.imshow('Video',canvas)
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()


### Pedistrians detection

In [37]:
body_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_fullbody.xml')

# Initiate video capture for video file

cap=cv2.VideoCapture('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/walking.avi')

# Loop once video is successfully loaded

while cap.isOpened():
    # Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    bodies=body_classifier.detectMultiScale(gray,1.2,3)
    
    # Extract bouning boxes for any bodies identified

    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2) 
        cv2.imshow('Pedistrians',frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

### Cars detection

In [42]:
import time

car_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_car.xml')

# Initiate video capture for video file

cap=cv2.VideoCapture('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/cars.avi')

# Loop once video is successfully loaded

while cap.isOpened():
    time.sleep(0.05)
    # Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    cars=car_classifier.detectMultiScale(gray,1.5,2)
    
    # Extract bouning boxes for any bodies identified

    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),1) 
        cv2.imshow('cars',frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

In [43]:
body_classifier=cv2.CascadeClassifier('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/Haarcascades/haarcascade_fullbody.xml')

# Initiate video capture for video file

cap=cv2.VideoCapture('F:/Naresh IT/DataScience Naresh I Technologies/DataScience/5. Artificial Intelligence or Deep Learning/Computer Vision/ImageforopenCV/surfing.avi')

# Loop once video is successfully loaded

while cap.isOpened():
    # Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    bodies=body_classifier.detectMultiScale(gray,1.2,3)
    
    # Extract bouning boxes for any bodies identified

    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),1) 
        cv2.imshow('surfing',frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()